name: Check Resource Links

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.md"

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: "**/*.md"
